TAGS = [
    "1v1", "2d", "2v2", "3v3", "4v4", "5v5", "6v6", "7v7", "8v8",
    "action", "ad", "adventure", "aim course", "arcade", "arena",
    "artistic", "atmospheric", "attack", "base", "base building",
    "battle", "battle royale", "board game", "boss battle",
    "boxfight", "building", "capture the flag", "card game",
    "casual", "choices matter", "classes", "clicker", "co-op",
    "collection", "competitive", "crafting", "creatures",
    "deathrun", "defend",
    "difficulty: easy", "difficulty: medium", "difficulty: hard",
    "difficulty: very hard", "difficulty: ultra hard", "difficulty: impossible",
    "driver simulator", "duo", "economy", "edit course",
    "educational", "episodic", "escape", "event", "exploration",
    "explosives", "farming simulator", "fashion", "fighting",
    "first person", "fortnitemares", "free for all", "friendly",
    "funny", "gun fight", "gun game", "hardcore", "heroes",
    "hide & seek", "horror", "hub", "infection", "jam system",
    "just for fun", "king of the hill", "melee", "memes",
    "minigame", "mining", "moba", "moving", "music", "mystery",
    "nonlinear", "objective", "one in the chamber", "one life",
    "one shot", "open world", "parkour", "party game", "party world",
    "patchwork", "peaceful", "physics", "pinball", "pixel art",
    "platformer", "point capture", "practice", "prop",
    "prop hunt", "puzzle", "pve", "pvp", "quiz", "race",
    "respawn", "retro", "roguelike", "role playing", "rounds",
    "rpg", "runner", "sandbox", "search & destroy", "seasonal",
    "secrets", "sequel", "series", "shooter", "shop", "show",
    "side scroller", "simulator", "single player", "skills",
    "sniper", "solo", "space", "sports", "squad", "stealth",
    "story", "strategy", "survival", "survival horror",
    "team deathmatch", "teams", "timed", "top-down",
    "tower defense", "training", "trios", "trivia",
    "turn-based", "tutorial", "tycoon", "unbalanced teams",
    "visual novel", "winterfest", "word games", "zonewars"
]